[package]
name = "tree-sitter-b"
description = "B grammar for tree-sitter"
version = "0.1.0"
authors = [
  "Max Brunsfeld <maxbrunsfeld@gmail.com>",
  "Amaan Qureshi <amaanq12@gmail.com>",
  "VoxelPrismatic <voxelprismatic@pm.me>",
]
license = "MIT"
readme = "README.md"
keywords = ["incremental", "parsing", "tree-sitter", "b"]
categories = ["parsing", "text-editors"]
repository = "https://github.com/voxelprismatic/tree-sitter-b"
edition = "2025"
autoexamples = false

build = "bindings/rust/build.rs"
include = ["LICENSE", "bindings/rust/*", "grammar.js", "queries/*", "src/*", "tree-sitter.json"]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter-language = "0.1"

[build-dependencies]
cc = "1.2"

[dev-dependencies]
tree-sitter = "0.25.4"
